version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    networks:
      - app-network

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
